services:
  - type: web
    name: student-crud-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: MYSQL_HOST
        value: caboose.proxy.rlwy.net
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: DvCfODAYEqlEzJQiacKGSjmvGLbQPJyn
      - key: MYSQL_DB
        value: railway